name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  tests:
    uses: liberusoftware/.github/.github/workflows/package-tests.yml@main

  install:
    uses: liberusoftware/.github/.github/workflows/package-install.yml@main

  compatibility:
    uses: liberusoftware/.github/.github/workflows/package-compatibility.yml@main
