apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: boilerplate-storage
  namespace: boilerplate-laravel
  labels:
    app: boilerplate-laravel
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
